### PR TITLE
Optimize Serialization

### PR DESCRIPTION
**Pull request by USBMenus**
Optimize serialization so user doesnt receive OutOfMemory error when trying to convert large files

### CODE REVIEW

**Comment by hafarooki** [comment]
Hi! I am surprised to receive a pull request on such an old project. I didn’t realize people still use this! I appreciate that you made a pull request for anyone who uses it to benefit. Looking at the changes, am I correct in understanding that essentially you just changed it from loading the file all at once to using a stream? I would be interested to know whether this still works with the new versions of MC where blocks and items don’t have fixed IDs anymore. I assume you have already tested these changes?

**Comment by USBMenus** [comment]
> Hi! I am surprised to receive a pull request on such an old project. I didn’t realize people still use this! I appreciate that you made a pull request for anyone who uses it to benefit. Looking at the changes, am I correct in understanding that essentially you just changed it from loading the file all at once to using a stream? I would be interested to know whether this still works with the new versions of MC where blocks and items don’t have fixed IDs anymore. I assume you have already tested these changes?

Yes, i only changed it to load from stream, but no i did not check to see if it works on the current version, i do apologize, i saw somewhere that said nothing past 1.13 will be saved to the schematic, i was trying to convert a model from tinkercad to blockbench but it didnt end up working, i was hesitant about making a pull request but figured maybe someone could benefit from it

**Comment by hafarooki** [comment]
Did you test it with a pre 1.13 version? In the past I think i basically converted the schematic to the old format using some world edit command

**Comment by USBMenus** [comment]
no i didnt test it at all, looking back, i prolly should have

**Pull request closed without merging**
